FROM alpine:latest

RUN apk update
RUN apk upgrade
RUN apk --no-cache add ttyd vim htop zsh busybox-extras curl
RUN adduser -D box --shell /bin/zsh

COPY motd /etc/motd

COPY zshrc /home/box/.zshrc
RUN chown box:box /home/box/.zshrc

USER box

EXPOSE 8080

CMD ttyd --once --cwd /home/box --port 8080 zsh
