FROM alpine:latest

RUN apk update
RUN apk upgrade
RUN apk --no-cache add ttyd vim htop zsh busybox-extras curl
RUN adduser -D box --shell /bin/zsh

USER box

EXPOSE 8080

CMD ttyd --once --port 8080 sh
