name: Push images to ECR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  ecr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["alpine", "ubuntu", "vscode", "dind"]
    steps:
      -
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - 
        name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ matrix.os }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ matrix.os }} -f Dockerfile-${{ matrix.os }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ matrix.os }}
